version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ABC
      MONGO_INITDB_ROOT_PASSWORD: ABC
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    ports:
      - "6333:6333"
      - "6334:6334"  # Optional: gRPC
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data:
