version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    build: .
    environment:
      BACKEND_STORE_URI: postgresql://mlflow_user:your_password@postgres:5432/mlflow_db
      ARTIFACT_ROOT: /mlflow/artifacts
      PORT: 5000
    ports:
      - "5000:5000"
    volumes:
      - ./artifacts:/mlflow/artifacts
    command:
      - mlflow
      - server
      - --backend-store-uri
      - postgresql://mlflow_user:your_password@postgres:5432/mlflow_db
      - --default-artifact-root
      - /mlflow/artifacts
      - --host
      - 0.0.0.0
      - --port
      - "5000"
    depends_on:
      - postgres

volumes:
  pgdata:
